#!/usr/bin/python3


freAddr = []
import os

ip = '192.168.31.'
for network in range(124, 130):
    package = os.popen('ping '+ip+str(network)).read()
    package = package.split('\n')[-3:]
    Minimum = package[0]
    if Minimum == 'Approximate round trip times in milli-seconds:':
        print( ip+str(network) + " is UP !")
    else:
        #print( 'Ping request could not find host ' + ip+str(network) )
        freAddr.append( 'Ping request could not find host '+ip+str(network))
print("Could not find hosts: ")
for free in freAddr:
    print(free)   

  
