#!/usr/bin/python3
import pymysql
import pandas as pd
from sqlalchemy import create_engine
import pandas as pd
import email, smtplib, ssl


db_host = "192.168.31.140"
db_user = "felix"
db_pwd = "administrator"
db_name = "store" 
db_charset = "utf8mb4"
path = "C:/Users/Vadym.Pyrozhenko/Desktop/PythonPostgres"
fileName = "example2.xlsx"

db_connection = f"mysql+pymysql://{db_user}:{db_pwd}@{db_host}/{db_name}?charset={db_charset}"
conn = create_engine(db_connection)

df = pd.read_sql("SELECT c.id, c.firstname, c.lastname, c.phone, a.amount, a.createdat FROM Customers AS c JOIN Accounts AS a ON a.customerid = c.id;", conn)
print(df)

df.to_excel(path + fileName, index=False)





from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

subject = "An email with attachment from Python"
body = "This is an email with attachment sent from Python"
sender_email = "vadimtinukr@gmail.com"
receiver_email = "vadimukrprofile@gmail.com"
password = "P!r0genk0123"

# Create a multipart message and set headers
message = MIMEMultipart()
message["From"] = sender_email
message["To"] = receiver_email
message["Subject"] = subject
message["Bcc"] = receiver_email  # Recommended for mass emails

# Add body to email
message.attach(MIMEText(body, "plain"))

filename = path + fileName  # In same directory as script

# Open PDF file in binary mode
with open(filename, "rb") as attachment:
    # Add file as application/octet-stream
    # Email client can usually download this automatically as attachment
    part = MIMEBase("application", "octet-stream")
    part.set_payload(attachment.read())

# Encode file in ASCII characters to send by email    
encoders.encode_base64(part)

# Add header as key/value pair to attachment part
part.add_header(
    "Content-Disposition",
    f"attachment; filename= {filename}",
)

# Add attachment to message and convert message to string
message.attach(part)
text = message.as_string()

# Log in to server using secure context and send email
context = ssl.create_default_context()
with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
    server.login(sender_email, password)
    server.sendmail(sender_email, receiver_email, text)
